config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("contests/", include("contests.urls")),
    path("", include("users.urls")),
]

contests/urls.py
from django.urls import path

from . import views

app_name = "contests"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("code_test/", views.code_test_view, name="code_test"),
    path("my_page/", views.my_page_view, name="my_page"),
    path("<str:short_name>/", views.contest_detail_view, name="contest_detail"),
    path("<str:short_name>/problems/", views.problems_view, name="problems"),
    path("<str:short_name>/problems/<int:problem_id>/", views.problem_detail_view, name="problem_detail"),
    path("<str:short_name>/submissions/", views.submissions_view, name="submissions"),
    path("<str:short_name>/submissions/me/", views.submissions_me_view, name="submissions_me"),
    path("<str:short_name>/submissions/<int:submission_id>/", views.submission_detail_view, name="submission_detail"),
    path("<str:short_name>/standings/", views.standings_view, name="standings"),
    # 編集ページ
    path("<str:short_name>/edit/", views.contest_detail_edit_view, name="contest_detail_edit"),
    path("<str:short_name>/problems/edit/", views.problems_edit_view, name="problems_edit"),
    path("<str:short_name>/problems/<int:problem_id>/edit/", views.problem_detail_edit_view, name="problem_detail_edit"),
    path("<str:short_name>/problems/<int:problem_id>/test_case/", views.test_case_edit_view, name="test_case_add"),     # 追加の場合はtest_case_idを指定しない
    path("<str:short_name>/problems/<int:problem_id>/test_case/<int:test_case_id>/", views.test_case_edit_view, name="test_case_edit"), # 編集の場合はtest_case_idを引数に渡す
    path("<str:short_name>/problems/<int:problem_id>/test_case/<int:test_case_id>/delete/", views.test_case_delete_view, name="test_case_delete"), # 削除
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

contests/forms.py
from django import forms

from colorfield.widgets import ColorWidget

from . import models


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile

        fields = ["color", "organization"]

        labels = {
            "color": "ユーザーカラー",
            "oorganization": "所属",
        }

        widgets = {
            "color": ColorWidget,
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["color"].widget.attrs["cols"] = "7"
        self.fields["organization"].widget.attrs["style"] = "width: 100%;"


class ContestEditForm(forms.ModelForm):
    """コンテスト編集用のフォーム"""
    class Meta:
        model = models.Contest
        fields = ["abstract", "penalty", "released"]

        labels = {
            "abstract": "概要",
            "penalty": "ペナルティ(分)",
            "released": "公開する",
        }
    
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)


class ProblemsAddForm(forms.ModelForm):
    class Meta:
        model = models.Problem
        fields = ("order", "title")


class ProblemEditForm(forms.ModelForm):
    """問題編集用のフォーム"""
    class Meta:
        model = models.Problem
        fields = ("order", "title", "question", "answer", "point")

        labels = {
            "order": "問題順序",
            "title": "タイトル",
            "question": "問題文",
            "answer": "答えのサンプル",
            "point": "配点",
        }


class TestCaseEditForm(forms.ModelForm):
    """テストケース 追加・編集 用フォーム"""
    class Meta:
        model = models.TestCase
        fields = ("title", "test_input", "test_output", "is_sample")

        labels = {
            "title": "タイトル",
            "test_input": "入力",
            "test_output": "出力",
            "is_sample": "これはサンプル",
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if key == "is_sample":
                continue
            field.widget.attrs["class"] = "form-control"
        self.fields["test_input"].widget.attrs["rows"] = 4
        self.fields["test_output"].widget.attrs["rows"] = 4


class SubmissionForm(forms.ModelForm):
    """解答提出用のフォーム"""
    class Meta:
        model = models.Submission
        fields = ("answer",)

        labels = {
            "answer": "解答",
        }
        help_texts = {
            "answer": "解答を入力",
        }


class CodeSubmissionForm(forms.Form):
    code = forms.CharField(
        widget=forms.Textarea,
        help_text="解答欄",
    )
    test_input = forms.CharField(
        widget=forms.Textarea,
        help_text="サンプル入力",
        required=False,
    )
    test_output = forms.CharField(
        widget=forms.Textarea,
        help_text="サンプル出力",
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["code"].widget.attrs["class"] = "form-control"
        self.fields["test_input"].widget.attrs["class"] = "form-control"
        self.fields["test_input"].widget.attrs["rows"] = "2"
        self.fields["test_output"].widget.attrs["class"] = "form-control"
        self.fields["test_output"].widget.attrs["rows"] = "2"

contests/views.py
import datetime
from threading import Thread

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import FormView
from django.contrib import messages

# 型アノテーションのためだけのimport...
from users.models import User

from . import models
from . import forms
from . import utils
from . import docker
from . import check_submission


class MyPageView(View):
    def get(self, request):
        context = {}
        if request.user.is_authenticated:
            context["contest_scores"] = models.ContestScore.objects.filter(user=request.user).order_by("-contest__start_date")
            # UserProfileの取得 or 新規作成
            try:
                user_profile = models.UserProfile.objects.get(user=request.user)
            except:
                user_profile = models.UserProfile.objects.create(user=request.user)
            context["user_profile"] = user_profile
            # UserProfileの変更フォーム
            form = forms.UserProfileForm(instance=user_profile)
            context["form"] = form
        return render(request, "contests/my_page.html", context)
    
    def post(self, request):
        if request.user.is_authenticated:
            user_profile = models.UserProfile.objects.get(user=request.user)
            form = forms.UserProfileForm(request.POST, instance=user_profile)
            if form.is_valid():
                form.save()
        return redirect("contests:my_page")

my_page_view = MyPageView.as_view()


class IndexView(View):
    def get(self, request, *args, **kwargs):
        now = timezone.now()
        all_contests = models.Contest.objects.all()
        past_contests = all_contests.filter(end_date__lt=now).order_by("-start_date")
        future_contests = all_contests.filter(start_date__gt=now).order_by("start_date")
        live_contests = all_contests.filter(start_date__lte=now).filter(end_date__gt=now)
        context = {
            "contests_list": [
                ("開催中のコンテスト", live_contests),
                ("開催予定のコンテスト", future_contests),
                ("過去のコンテスト", past_contests),
            ],
        }
        return render(request, "contests/index.html", context)

index_view = IndexView.as_view()


def enter_contest(contest: models.Contest, user: User):
    """コンテスト参加時の処理をすべて行う．\
    元から存在する場合は初期化する．(得点再計算を考慮)
    """
    
    # コンテストに参加
    if user not in contest.users.all():
        contest.users.add(user)
        contest.save()
    
    # スコアの初期化
    # ContestScoreの初期化
    try:    # 存在する場合
        contest_score = models.ContestScore.objects.get(contest=contest, user=user)
    except: # 存在しない場合は作成
        contest_score = models.ContestScore.objects.create(
            contest=contest,
            user=user,
        )
    contest_score.time_sec = 0
    contest_score.penalty = 0
    contest_score.score = 0
    contest_score.save()
    for problem in contest.problem_set.all():
        # ProblemScoreの初期化
        try:    # 存在する場合
            problem_score = models.ProblemScore.objects.get(user=user, problem=problem)
        except: # 存在しない場合は作成
            problem_score = models.ProblemScore.objects.create(
                user=user,
                problem=problem,
            )
        problem_score.time_sec = 0
        problem_score.penalty = 0
        problem_score.score = 0
        problem_score.save()

class ContestDetailView(View):
    def get(self, request, short_name, *args, **kwargs):
        contest = get_object_or_404(models.Contest, short_name=short_name)
        try:
            author = models.Author.objects.get(contest=contest)
        except:
            author = models.Author.objects.create(contest=contest)
            author.save()
        context = {
            "is_live": contest.is_live(),
            "contest": contest,
            "author": author,
            "problems": contest.problem_set.order_by("order"),
            # "start_date_str": contest.get_start_time_str(),
            # "end_date_str": contest.get_end_time_str(),
        }
        return render(request, "contests/contest_detail.html", context)
    
    def post(self, request, short_name, *args, **kwargs):
        contest = get_object_or_404(models.Contest, short_name=short_name)
        if request.user.is_authenticated:   # ログイン済ユーザー
            # コンテスト参加処理
            enter_contest(contest, request.user)
            return redirect("contests:contest_detail", short_name)
        else:
            return redirect("users:index")

contest_detail_view = ContestDetailView.as_view()


class ProblemsView(View):
    def get(self, request, short_name, *args, **kwargs):
        contest = get_object_or_404(models.Contest, short_name=short_name)
        context = {
            "contest": contest,
            "problems": contest.problem_set.order_by("order"),
        }
        return render(request, "contests/problems.html", context)

problems_view = ProblemsView.as_view()


def update_submission(submission: models.Submission, problem: models.Problem, user: User):
    """Submissionの正誤判定と保存
    """
    # user, problemの関連づけ．check_submission内でproblemを取得するため．
    submission.user = user
    submission.problem = problem
    submission.accepted = True  # ACであると仮定しておく．
    submission.total_test_case = problem.total_test_case()    # テストケースの数
    # いったん保存する．test_resultでforeignkeyとして使用するため．
    submission.save()
    # acceptedの更新は冗長な処理になってしまっている
    if check_submission.check_answer(submission):   # 正答
        submission.status = "AC"
        submission.accepted = True
        submission.point = problem.point
    else:   # 誤答
        submission.accepted = False
    # 保存
    submission.save()

def update_contest_score(problem_score: models.ProblemScore, contest: models.Contest, user: User):
    """ContestScoreの更新
    """
    # ContestScoreの更新
    try:
        contest_score = models.ContestScore.objects.get(contest=contest, user=user)
    except: # 念のため
        contest_score = models.ContestScore.objects.create(
            contest=contest,
            user=user,
        )
    contest_score.penalty += problem_score.penalty      # ペナルティ加算
    contest_score.score += problem_score.score          # スコア加算
    # 時間(s) = 最終の初ACの時間(s) + ペナルティ数 * ペナルティ * 60
    contest_score.time_sec = problem_score.time_sec + contest_score.penalty * contest.penalty * 60
    contest_score.save()    # 保存

def update_problem_score(submission: models.Submission, contest: models.Contest, problem: models.Problem, user: User):
    """スコア(ContestScore, ProblemScore)の更新
    """

    # ProblemScoreの更新
    try:
        problem_score = models.ProblemScore.objects.get(user=user, problem=problem)
    except: # 念のため
        problem_score = models.ProblemScore.objects.create(
            user=user,
            problem=problem,
        )
    
    # まだACしていない場合，スコア変動の可能性がある
    if problem_score.time_sec == 0:
        if submission.accepted: # AC：時間(s)と得点を更新
            problem_score.time_sec = (submission.submission_date - contest.start_date).total_seconds() # 時間更新
            problem_score.score = submission.point  # 得点を更新
            
            # ContestScoreを更新
            update_contest_score(problem_score, contest, user)
        else:   # WA：ペナルティ加算
            problem_score.penalty += 1
    
    problem_score.save()    # 保存

def submit(submission: models.Submission, contest: models.Contest, problem: models.Problem, user: User, force_to_rescore: bool=False):
    """submissionを受け取って，正誤判定を行い，関連するデータベースを更新する
    """
    # Submissionの更新
    update_submission(submission, problem, user)

    # スコアの更新
    if contest.is_live() or force_to_rescore:   # 開催中 or 強制再計算の場合のみ得点計算
        # ProblemScoreの更新．必要に応じて，ContestScoreの更新も行われる
        update_problem_score(submission, contest, problem, user)

class ProblemDetailView(View):
    def get(self, request, short_name, problem_id, *args, **kwargs):
        contest = get_object_or_404(models.Contest, short_name=short_name)
        problem = get_object_or_404(models.Problem, pk=problem_id)
        test_cases = models.TestCase.objects.filter(problem=problem, is_sample=True)
        context = {
            "contest": contest,
            "problem": problem,
            "form": forms.SubmissionForm(),
            "test_cases": test_cases,
        }
        return render(request, "contests/problem_detail.html", context)
    
    def post(self, request, short_name, problem_id, *args, **kwargs):
        contest = get_object_or_404(models.Contest, short_name=short_name)
        problem = get_object_or_404(models.Problem, pk=problem_id)
        form = forms.SubmissionForm(request.POST)
        if form.is_valid(): # 検証ずみ
            submission = form.save(commit=False)    # DBに保存せずにインスタンス化
            # 提出処理
            # submit(submission, contest, problem, request.user, force_to_rescore=False)
            # スレッドに任せる
            thread = Thread(target=submit, args=(submission, contest, problem, request.user, False,))
            thread.start()
            # リダイレクト
            return redirect("contests:submissions", short_name)
        else:   # 検証エラー
            test_cases = models.TestCase.objects.filter(problem=problem, is_sample=True)
            context = {
                "contest": contest,
                "problem": problem,
                "form": form,
                "test_cases": test_cases,
            }
            return render(request, "contests/problem_detail.html", context)

problem_detail_view = ProblemDetailView.as_view()


class SubmissionsView(View):
    def get(self, request, short_name, *args, **kwargs):
        if not request.user.is_authenticated:   # 要ログイン
            return redirect("users:index")
        contest = get_object_or_404(models.Contest, short_name=short_name)
        submissions = models.Submission.objects.filter(problem__contest=contest).order_by("-submission_date")
        if contest.is_live():   # 開催中はユーザは自分の提出のみ見られる

contests/templates/contests/contest_detail.html
{% extends 'contests/contest_base.html' %}

{% block contest_tab_detail %}active{% endblock %}

{% block contest_content %}
<div class="col-sm-12 mb-4 pl-4 pr-4 pb-4 text-center bg-light">
    {% comment %} コンテストタイトル {% endcomment %}
    <h1 class="pt-4">{{contest.title}}</h1>
    {% comment %} 参加ボタン {% endcomment %}
    <div class="pt-1 pb-4">
        {% if not contest.is_past_contest %}
            {% if user not in contest.users.all %}
                {% comment %} コンテストが開催中or予定されて，userが参加していない場合 {% endcomment %}
                <form action="" method="POST" class="p-3">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-lg">参加する</button>
                </form>
            {% else %}
                {% comment %} 参加済 {% endcomment %}
                <div class="p-3">
                    <button type="button" class="btn btn-secondary btn-lg" disabled>参加済</button>
                </div>
            {% endif %}
        {% endif %}
        {% if user in author.users.all %}
            <a class="btn btn-success" href="{% url 'contests:contest_detail_edit' contest.short_name %}">編集</a>
        {% endif %}
    </div>
</div>

<div class="col-sm-12 mb-4">
    <h3>コンテスト情報</h3>
    <ul>
        <li>コンテスト時間: {{ contest.get_time_hour }}分</li>
        <li>writer: {{ author.get_author_names_str|safe }}</li>
        <li>ペナルティ: {{ contest.penalty }}分</li>
    </ul>
</div>

<div class="col-sm-12">
    <h3>配点</h3>
    <table class="table table-bordered table-striped text-center">
        <thead>
            <tr class="">
                <th>問題</th>
                <th>点数</th>
            </tr>
        </thead>
        <tbody>
            {% for problem in problems %}
                <tr>
                    <td>{{problem.order}}</td>
                    <td>{{problem.point}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="col-sm-12">
    <h3>ルール</h3>
    <ol>
        <li>コンテスト中に問題に正解すると得点を獲得できます。</li>
        <li>順位は総合得点で決定します。</li>
        <li>同点の場合は提出時間の早い人が上の順位になります。</li>
        <li>誤答を提出するたびにペナルティが加算されます。このコンテストのペナルティは{{contest.penalty}}分です。</li>
    </ol>
</div>

{% endblock contest_content %}

contests/templates/contests/contest_edit_base.html
{% extends 'base.html' %}


{% block page_title %}
    Edit:{{contest.short_name}}
{% endblock page_title %}


{% block content %}

{% if user in contest.author.users.all %}

    {% comment %} 編集ページ共通のバー {% endcomment %}
    <div class="row">
        <div class="col-12 mt-4 text-center">
            <h3>{{contest.title}}</h3>
        </div>
        <div class="col-12">
            <ul class="nav nav-tabs navbar-dark mb-4">
                <li class="nav-item">
                    <a class="nav-link {% block contest_tab_detail %}{% endblock %}" href="{% url 'contests:contest_detail_edit' contest.short_name %}">
                        {% include 'icons/house-fill.svg' %}
                        トップ
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block contest_tab_problems %}{% endblock %}" href="{% url 'contests:problems_edit' contest.short_name %}">
                        {% include 'icons/list-task.svg' %}
                        問題
                    </a>
                </li>
            </ul>
        </div>
    </div>


    {% block contest_content %}
    {% comment %} オーバーライド {% endcomment %}
    {% endblock contest_content %}

{% else %}

<div class="row p-5">
    <div class="col-sm-12 text-center">
        <h3>不正なアクセス</h3>
    </div>
</div>

{% endif %}

{% endblock content %}

contests/templates/contests/my_page.html
{% extends 'base.html' %}

{% block content %}
<div class="row p-3">
    {% if user.is_authenticated %}
        <div class="col-sm-12 text-center">
            <h2>
                {{user.get_colored_username|safe}}
                <small>さんのマイページ</small>
            </h2>
        </div>
        <hr>
        <div class="col-sm-12 mt-4">
            <h3>プロフィール</h3>
            <div class="row mt-3">
                <div class="col-sm-3">ユーザー名：</div>
                <div class="col-sm-4 mb-3">
                    {{user.get_colored_username|safe}}
                </div>
            </div>
            {{form.media}}
            <div class="row">
                <form action="" method="post">{% comment %} ユーザーカラーの変更フォーム {% endcomment %}
                    {% csrf_token %}
                    <div class="col-sm mb-3">
                        {{form.color.label}}
                        {{form.color}}
                    </div>
                    <div class="col-sm-12 mb-3">
                        {{form.organization.label}}
                        {{form.organization}}
                    </div>
                    <div class="col-sm-2 mb-4">
                        <button class="btn btn-primary btn-sm">変更</button>
                    </div>
                </form>
            </div>
        </div>
        <hr>
        <div class="col-sm-12 mt-4">
            <h3>コンテスト成績</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>日時</th>
                        <th>コンテスト名</th>
                        {% comment %} 順位も表示したい {% endcomment %}
                        <th>順位</th>   
                    </tr>
                </thead>
                <tbody>
                    {% for contest_score in contest_scores %}
                        {% if contest_score.contest.is_past_contest %}
                            <tr>
                                <td>{{contest_score.contest.get_start_time_str}}</td>
                                <td>{{contest_score.contest.title}}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-12 mt-4">
            <a class="btn btn-outline-secondary" href="{% url 'users:logout' %}">ログアウト</a>
        </div>
        {% if user.is_superuser %}
            <div class="col-sm-12 mt-4">
                管理者アカウントです
                <a class="btn btn-primary" href="{% url 'admin:index' %}">アドミン</a>
            </div>
        {% endif %}
    {% else %}
        <div class="col-sm-12 text-center">
            <h2>ゲストユーザー</h2>
        </div>
        <hr>
        <div class="col-sm-12 text-center">
            <a class="btn btn-outline-primary" href="{% url 'users:login' %}">ログイン</a>
            もしくは
            <a class="btn btn-outline-primary" href="{% url 'users:signup' %}">新規登録</a>
        </div>
    {% endif %}
</div>
{% endblock content %}

contests/templates/contests/problem_detail_edit.html
{% extends 'contests/contest_edit_base.html' %}


{% block contest_tab_problems %}active{% endblock contest_tab_problems %}


{% block contest_content %}

<div class="row ps-5 pe-5">
    <div class="col-sm-12">
        <h3>問題編集ページ</h3>
    </div>
</div>
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="row ps-5 pe-5">
            <div class="col-sm-12 form-label">
                {{field.label}}
            </div>
            <div class="col-sm-12 mb-3">
                {{field}}
            </div>
            {% if field.errors %}
                <div class="col-sm-12">
                    <span class="error_message">
                        {{field.errors}}
                    </span>
                </div>
            {% endif %}
        </div>
    {% endfor %}
    <div class="col-sm-12 mb-3 ms-5">
        <button class="btn btn-primary">変更</button>
    </div>
</form>
<div class="row ps-5 pe-5 pt-3">
    <div class="col-sm-12">
        <h3>テストケース</h3>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th width="10%">テストケース名</th>
                <th width="30%">入力</th>
                <th width="30%">出力</th>
                <th width="10%"></th>
                <th width="10%"></th>
            </tr>
        </thead>
        <tbody>
            {% for test_case in test_cases %}
                <tr>
                    <td>{{test_case.title}}</td>
                    <td>{{test_case.test_input}}</td>
                    <td>{{test_case.test_output}}</td>
                    <td>
                        <a href="{% url 'contests:test_case_edit' contest.short_name problem.pk test_case.pk %}" class="btn btn-primary btn-sm">編集</a>
                    </td>
                    <td>
                        <form method="post" action="{% url 'contests:test_case_delete' contest.short_name problem.pk test_case.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-sm">削除</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td class="text-center" colspan="3"><a href="{% url 'contests:test_case_add' contest.short_name problem.pk %}" class="btn btn-primary btn-sm">追加</a></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock contest_content %}

contests/templates/contests/problems.html
{% extends 'contests/contest_base.html' %}

{% block contest_tab_problems %}active{% endblock %}

{% block contest_content %}
<div class="col-sm-12">
    <h3>問題</h3>
    <hr>
</div>
{% if contest.is_future_contest %}
    {% comment %} 開催予定のコンテスト {% endcomment %}
    <div class="col-sm-12">
        開催していません
    </div>
{% elif contest.is_live and user not in contest.users.all %}
    {% comment %} 開催中だが参加していない {% endcomment %}
    <div class="col-sm-12">
        開催していません
    </div>
{% else %}
    {% comment %} それ以外の場合は見られる {% endcomment %}
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th width="5%"></th>
                <th>問題名</th>
            </tr>
        </thead>
        <tbody>
            {% for problem in problems %}
                <tr>
                    <td class="text-center"><a href="{% url 'contests:problem_detail' contest.short_name problem.pk %}">{{problem.order}}</a></td>
                    <td><a href="{% url 'contests:problem_detail' contest.short_name problem.pk %}">{{problem.title}}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

{% endblock contest_content %}

contests/templates/contests/problems_edit.html
{% extends 'contests/contest_edit_base.html' %}


{% block contest_tab_problems %}active{% endblock contest_tab_problems %}


{% block contest_content %}
<div class="row ps-5 pe-5">
    <div class="col-sm-12">
        <h3>問題一覧</h3>
    </div>
</div>
<div class="row ps-5 pe-5">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th width="5%"></th>
                <th>問題名</th>
                <th>配点</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for problem in problems %}
                <tr>
                    <td class="text-center">
                        <a href="{% url 'contests:problem_detail' contest.short_name problem.pk %}">{{problem.order}}</a>
                    </td>
                    <td>
                        <a href="{% url 'contests:problem_detail' contest.short_name problem.pk %}">{{problem.title}}</a>
                    </td>
                    <td>
                        {{problem.point}}
                    </td>
                    <td>
                        <a href="{% url 'contests:problem_detail_edit' contest.short_name problem.pk %}" class="btn btn-primary btn-sm">編集</a>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <form action="" method="post">
                    {% csrf_token %}
                    <td>
                        {{form.order}}
                        <span class="error_message">
                            {{form.order.errors}}
                        </span>
                    </td>
                    <td>
                        {{form.title}}
                        <span class="error_message">
                            {{form.title.errors}}
                        </span>
                    </td>
                    <td></td>
                    <td><button class="btn btn-primary btn-sm">追加</button></td>
                </form>
            </tr>
        </tbody>
    </table>
    {{form.non_field_error}}
</div>
{% endblock contest_content %}

contests/templates/contests/submissions.html
{% extends 'contests/contest_base.html' %}

{% block contest_tab_submissions %}active{% endblock %}

{% block contest_content %}

<div class="col-sm-12">
    <h3>提出一覧</h3>
</div>
{% if user not in contest.users.all and not contest.is_past_contest %}
    <p>参加してください</p>
{% else %}
    {% comment %} 開催中は自分の提出しか見れないようになっている {% endcomment %}
    {% comment %} コンテスト終了後は全ての提出が見られる {% endcomment %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>提出日時</th>
                <th>問題</th>
                <th>ユーザ</th>
                <th>得点</th>
                <th>結果</th>
                <th>詳細</th>
            </tr>
        </thead>
        {% for submission in submissions %}
            <tbody>
                <tr>
                    <td>{{ submission.get_date_str }}</td>
                    <td>
                        <a href="{% url 'contests:problem_detail' contest.short_name submission.problem.id %}">
                            {{ submission.problem.title }}
                        </a>
                    </td>
                    <td>{{ submission.user.get_colored_username|safe }}</td>
                    <td>{{ submission.point }}</td>
                    <td>
                        {% if submission.judged_test_case < submission.total_test_case %} {% comment %} ジャッジ中 {% endcomment %}
                            <span class="badge label-waiting-judge {% if not submission.accepted %}label-warning{% endif %}">
                                {{submission.judged_test_case}}/{{submission.total_test_case}}
                            </span>
                        {% else %} {% comment %} 結果が確定 {% endcomment %}
                            <span class="badge label-{% if submission.accepted %}success{% else %}warning{% endif %}">
                                {{ submission.status }}
                            </span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'contests:submission_detail' contest.short_name submission.id %}">
                            詳細
                        </a>
                    </td>
                </tr>
            </tbody>
        {% endfor %}
    </table>
{% endif %}

{% endblock contest_content %}