config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("contests/", include("contests.urls")),
    path("", include("users.urls")),
]

contests/urls.py
from django.urls import path

from . import views

app_name = "contests"
urlpatterns = [
    path("", views.index_view, name="index"),
    path("code_test/", views.code_test_view, name="code_test"),
    path("my_page/", views.my_page_view, name="my_page"),
    path("<str:short_name>/", views.contest_detail_view, name="contest_detail"),
    path("<str:short_name>/problems/", views.problems_view, name="problems"),
    path("<str:short_name>/problems/<int:problem_id>/", views.problem_detail_view, name="problem_detail"),
    path("<str:short_name>/submissions/", views.submissions_view, name="submissions"),
    path("<str:short_name>/submissions/me/", views.submissions_me_view, name="submissions_me"),
    path("<str:short_name>/submissions/<int:submission_id>/", views.submission_detail_view, name="submission_detail"),
    path("<str:short_name>/standings/", views.standings_view, name="standings"),
    # 編集ページ
    path("<str:short_name>/edit/", views.contest_detail_edit_view, name="contest_detail_edit"),
    path("<str:short_name>/problems/edit/", views.problems_edit_view, name="problems_edit"),
    path("<str:short_name>/problems/<int:problem_id>/edit/", views.problem_detail_edit_view, name="problem_detail_edit"),
    path("<str:short_name>/problems/<int:problem_id>/test_case/", views.test_case_edit_view, name="test_case_add"),     # 追加の場合はtest_case_idを指定しない
    path("<str:short_name>/problems/<int:problem_id>/test_case/<int:test_case_id>/", views.test_case_edit_view, name="test_case_edit"), # 編集の場合はtest_case_idを引数に渡す
    path("<str:short_name>/problems/<int:problem_id>/test_case/<int:test_case_id>/delete/", views.test_case_delete_view, name="test_case_delete"), # 削除
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

templates/components/login_link.html
<a class="btn btn-primary" href="{% url 'users:login' %}">ログイン</a>

templates/components/signup_link.html
<a class="btn btn-success" href="{% url 'users:signup' %}">新規登録</a>

templates/components/top_bar.html
{% load static %}

{% comment %} すべてのページのヘッダー {% endcomment %}
{% block header %}
{% comment %} 必要ないページではオーバーライドする {% endcomment %}
{% comment %} 結局しなかった． {% endcomment %}
<header>
<!-- Fixed navbar -->
    <nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
        <div class="container-fluid">
            {% comment %} ブランドロゴリンク {% endcomment %}
            <a class="navbar-brand" href="{% url 'contests:index' %}">
                <img id="img_logo" src="{% static 'images/logo.png' %}" alt="MatCoder">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav_toggle" aria-controls="nav-toggle" aria-expand="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="nav_toggle">
                <ul class="navbar-nav me-auto mb-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'contests:index' %}">コンテスト</a>
                    </li>
                </ul>
                <div class="d-flex navbar-nav me-0 mb-lg-0">
                    {% if user.is_authenticated %}
                        {% comment %} ログイン済の場合はマイページ {% endcomment %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:index' %}">{{user.username}}</a>
                        </li>
                    {% else %}
                        {% comment %} 未ログインの場合はログイン/新規登録 {% endcomment %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:signup' %}">新規登録</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">ログイン</a>
                        </li>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
{% endblock header %}